repos:

  - repo: https://github.com/seddonym/import-linter
    rev: v2.5
    hooks:
    - id: import-linter

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.6.0"
    hooks:
    -   id: djade
        args: [--target-version, "5.1"]  # Use current Django version


  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.6.0"
    hooks:
      - id: tox-ini-fmt
        args: [ "-p", "lint" ]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
      - id: ruff-format
        args:
          - --check

  - repo: https://github.com/saxix/pch
    rev: '0a8492b'
    hooks:

      - id: check-missed-migrations
        args:
          - src
        stages: [ pre-commit ]
        additional_dependencies: [ setuptools ]

      - id: check-untracked
        args:
          - src
          - tests
        stages: [ pre-push ]

      - id: check-forbidden
        args:
          - -i
          - "pyproject.toml"
          - -p
          - "/\\[tool.uv.sources\\]/"
        stages: [ pre-push ]

      - id: check-tailwind
        name: check tailwind CSS ready for production
        files: src/hope_live/theme/static_src/src/styles.scss
        entry: python /Users/sax/Documents/data/PROGETTI/saxix/pch/src/pch/check_tailwind.py
        args:
          - -o
          - src/hope_live/theme/static/css/styles.css

      - id: check-minimized
        name: check missing minimized javascript
        files: (\.js)$
        args:
          - -i
          - "src/hope_live/theme/static_src/*.js"
