site_name: HOPE Live Dashboard
docs_dir: docs
copyright: Copyright &copy; 2025
repo_url: https://github.com/UNICEF/hope-live-dashboard
site_author: saxix
site_dir: ./~build/docs


markdown_extensions:
  - admonition
#  - pymdownx.magiclink
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
#  - pymdownx.snippets:
#      base_path: '.'
#      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: "material"
  color_mode: auto
#  custom_dir: docs/_theme/overrides
#  favicon: img/favicon.ico
#  logo: img/logo.png
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  user_color_mode_toggle: true
  features:
#    - content.action.edit
    - content.code.annotate
    - content.code.copy
#    - content.tooltips
#    - header.autohidex
#    - navigation.footer
#    - navigation.indexes
#    - navigation.instant
#    - navigation.instant.prefetch
#    - navigation.instant.progress
#  extra:
#    version:
#      provider: mike
#      alias: true
#    languages:
#      - lang_code: en
#        lang_name: English
#      - lang_code: it
#        lang_name: Italian
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - mkdocstrings:
      default_handler: python
#  - awesome-pages
  - search
#  - include-markdown:
#      encoding: ascii
#      preserve_includer_indent: false
#      dedent: false
#      trailing_newlines: true
#      comments: false
#      rewrite_relative_urls: true
#      heading_offset: 0
#      recursive: true
