[mypy]
files = src/
;packages = hope_live
mypy_path = $MYPY_CONFIG_FILE_DIR/src:$MYPY_CONFIG_FILE_DIR/tests/_demoapp
;enable_error_code =
;    deprecated,
;    ignore-without-code
;plugins =
;    mypy_django_plugin.main

strict = true



[mypy.plugins.django-stubs]
django_settings_module = hope_live_dashboard.config.settings

[mypy-django_regex.*]
ignore_errors = true
ignore_missing_imports = True

[mypy-flags.*]
ignore_errors = true
ignore_missing_imports = True

[mypy-smart_env.*]
ignore_errors = true
ignore_missing_imports = True
