[mypy]
files = src/
mypy_path = $MYPY_CONFIG_FILE_DIR/src:$MYPY_CONFIG_FILE_DIR/tests/_demoapp
plugins =
    mypy_django_plugin.main

strict = true

[mypy.plugins.django-stubs]
django_settings_module = hope_live.config.settings

# Ignore errors for external packages
[mypy-*.migrations.*]
ignore_errors = true

[mypy-constance.*]
ignore_missing_imports = true

[mypy-debug_toolbar.*]
ignore_missing_imports = true

[mypy-django.*]
ignore_missing_imports = true

[mypy-django_regex.*]
ignore_missing_imports = true

[mypy-flags.*]
ignore_missing_imports = true

[mypy-smart_env.*]
ignore_missing_imports = true

[mypy-social_django.*]
ignore_missing_imports = true

[mypy-unfold.*]
ignore_missing_imports = true

[mypy-unicef_security.*]
ignore_missing_imports = true

[mypy-celery.*]
ignore_missing_imports = true

[mypy-channels.*]
ignore_missing_imports = true

[mypy-django_allauth.*]
ignore_missing_imports = true

[mypy-django_cors_headers.*]
ignore_missing_imports = true

[mypy-django_extensions.*]
ignore_missing_imports = true

[mypy-django_filters.*]
ignore_missing_imports = true

[mypy-django_redis.*]
ignore_missing_imports = true

[mypy-djangorestframework.*]
ignore_missing_imports = true

[mypy-drf_spectacular.*]
ignore_missing_imports = true

[mypy-pika.*]
ignore_missing_imports = true

[mypy-psycopg2.*]
ignore_missing_imports = true

[mypy-redis.*]
ignore_missing_imports = true

# Ignore errors for unmanaged models
[mypy-hope_live.models.hope.*]
ignore_errors = true
