[pytest]
django_find_project = false
pythonpath = ./src
DJANGO_SETTINGS_MODULE = hope_live.config.settings
norecursedirs = demo,.tox
addopts =
    --capture=no
    --tb=short
    --create-db
    -x -n auto
    --cov=streaming
    --cov-config=tests/.coveragerc
    --cov-report html
log_cli = false
log_level = CRITICAL
log_format = %(levelname)s %(name)s: %(message)s


python_files =
    tests/test_*.py
    tests/**/test_*.py
    src/*.py

markers =
    functional: mark a test as functional
    selenium: selenium test
    skip: skip test
    online: mark a test as requiring network access
    withoutresponses: disable responses mocking
    skip_buttons:
    skip_models:
