# Generated by Django 5.2.6 on 2025-09-18 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hope_live", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("hope_id", models.CharField(blank=True, default="", max_length=100, unique=True)),
                ("name", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("long_name", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("code", models.CharField(blank=True, db_index=True, default="", max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, default="", max_length=100, unique=True)),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Is this office active in the HOPE core?"
                    ),
                ),
                ("kobo_country_code", models.CharField(blank=True, default="", max_length=3)),
                ("extra_fields", models.JSONField(blank=True, default=dict)),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Is this office enabled in the workspace?"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("hope_id", models.CharField(editable=False, max_length=200, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(db_index=True, max_length=10)),
                ("sector", models.CharField(db_index=True, max_length=50)),
                (
                    "country_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="programs", to="hope_live.office"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("expires", models.DateField(blank=True, null=True)),
                (
                    "country_office",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hope_live.office"),
                ),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.group")),
                (
                    "program",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="hope_live.program"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="roles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "country_office", "group"), name="hope_live_userrole_unique_role"
                    )
                ],
            },
        ),
    ]
