# Generated by Django 5.2.10 on 2026-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("country_slug", models.CharField(db_index=True, max_length=100)),
                ("dimension_type", models.CharField(db_index=True, max_length=50)),
                ("dimension_value", models.CharField(db_index=True, max_length=255)),
                ("total_usd", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("total_qty", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("payment_count", models.IntegerField(default=0)),
                ("total_beneficiaries", models.IntegerField(default=0)),
                ("total_children", models.IntegerField(default=0)),
                ("total_pwd", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["dimension_type", "date"], name="hope_analys_dimensi_4b1364_idx"),
                    models.Index(fields=["country_slug", "dimension_type"], name="hope_analys_country_e912c9_idx"),
                ],
                "unique_together": {("date", "country_slug", "dimension_type", "dimension_value")},
            },
        ),
    ]
