# Generated by Django 5.2.10 on 2026-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hope_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dailyaggregate",
            index=models.Index(
                fields=["dimension_type", "country_slug", "date"], name="hope_analys_dimensi_55cee1_idx"
            ),
        ),
    ]
