# Generated by Django 5.2.12 on 2026-03-18 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_syncdailyaggregatesjob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="syncdailyaggregatesjob",
            options={
                "default_permissions": ("add", "change", "delete", "view", "queue", "terminate", "inspect", "revoke"),
                "verbose_name": "Sync Daily Aggregates Job",
                "verbose_name_plural": "Sync Daily Aggregates Jobs",
            },
        ),
        migrations.RemoveField(
            model_name="syncdailyaggregatesjob",
            name="action",
        ),
        migrations.RemoveField(
            model_name="syncdailyaggregatesjob",
            name="config",
        ),
        migrations.RemoveField(
            model_name="syncdailyaggregatesjob",
            name="sentry_id",
        ),
        migrations.RemoveField(
            model_name="syncdailyaggregatesjob",
            name="type",
        ),
    ]
