# Generated by Django 5.2.12 on 2026-03-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_alter_syncdailyaggregatesjob_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncdailyaggregatesjob",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
