# Generated by Django 5.2.13 on 2026-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_syncdailyaggregatesjob_error_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletionAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                (
                    "time_grain",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        db_index=True,
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("country_slug", models.CharField(db_index=True, max_length=100)),
                ("dimension_type", models.CharField(db_index=True, max_length=50)),
                ("dimension_value", models.CharField(db_index=True, max_length=255)),
                ("payment_count", models.IntegerField(default=0)),
                ("total_usd", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DemographicAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                (
                    "time_grain",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        db_index=True,
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("country_slug", models.CharField(db_index=True, max_length=100)),
                ("dimension_type", models.CharField(db_index=True, max_length=50)),
                ("dimension_value", models.CharField(db_index=True, max_length=255)),
                ("total_beneficiaries", models.IntegerField(default=0)),
                ("total_children", models.IntegerField(default=0)),
                ("total_pwd", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FinancialAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                (
                    "time_grain",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        db_index=True,
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("country_slug", models.CharField(db_index=True, max_length=100)),
                ("dimension_type", models.CharField(db_index=True, max_length=50)),
                ("dimension_value", models.CharField(db_index=True, max_length=255)),
                ("total_usd", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("total_qty", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("payment_count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GrievanceAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                (
                    "time_grain",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        db_index=True,
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("country_slug", models.CharField(db_index=True, max_length=100)),
                ("dimension_type", models.CharField(db_index=True, max_length=50)),
                ("dimension_value", models.CharField(db_index=True, max_length=255)),
                ("ticket_count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="DailyAggregate",
        ),
        migrations.AlterField(
            model_name="syncdailyaggregatesjob",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="completionaggregate",
            index=models.Index(fields=["dimension_type", "date"], name="analysis_co_dimensi_386ab3_idx"),
        ),
        migrations.AddIndex(
            model_name="completionaggregate",
            index=models.Index(fields=["country_slug", "dimension_type"], name="analysis_co_country_a983f1_idx"),
        ),
        migrations.AddIndex(
            model_name="completionaggregate",
            index=models.Index(
                fields=["dimension_type", "country_slug", "date", "time_grain"], name="analysis_co_dimensi_ceb8ec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="completionaggregate",
            unique_together={("date", "time_grain", "country_slug", "dimension_type", "dimension_value")},
        ),
        migrations.AddIndex(
            model_name="demographicaggregate",
            index=models.Index(fields=["dimension_type", "date"], name="analysis_de_dimensi_b16ffe_idx"),
        ),
        migrations.AddIndex(
            model_name="demographicaggregate",
            index=models.Index(fields=["country_slug", "dimension_type"], name="analysis_de_country_d22910_idx"),
        ),
        migrations.AddIndex(
            model_name="demographicaggregate",
            index=models.Index(
                fields=["dimension_type", "country_slug", "date", "time_grain"], name="analysis_de_dimensi_c0ada7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="demographicaggregate",
            unique_together={("date", "time_grain", "country_slug", "dimension_type", "dimension_value")},
        ),
        migrations.AddIndex(
            model_name="financialaggregate",
            index=models.Index(fields=["dimension_type", "date"], name="analysis_fi_dimensi_8cae39_idx"),
        ),
        migrations.AddIndex(
            model_name="financialaggregate",
            index=models.Index(fields=["country_slug", "dimension_type"], name="analysis_fi_country_a2b096_idx"),
        ),
        migrations.AddIndex(
            model_name="financialaggregate",
            index=models.Index(
                fields=["dimension_type", "country_slug", "date", "time_grain"], name="analysis_fi_dimensi_f8d506_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialaggregate",
            unique_together={("date", "time_grain", "country_slug", "dimension_type", "dimension_value")},
        ),
        migrations.AddIndex(
            model_name="grievanceaggregate",
            index=models.Index(fields=["dimension_type", "date"], name="analysis_gr_dimensi_0ba368_idx"),
        ),
        migrations.AddIndex(
            model_name="grievanceaggregate",
            index=models.Index(fields=["country_slug", "dimension_type"], name="analysis_gr_country_8d6ee5_idx"),
        ),
        migrations.AddIndex(
            model_name="grievanceaggregate",
            index=models.Index(
                fields=["dimension_type", "country_slug", "date", "time_grain"], name="analysis_gr_dimensi_037439_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grievanceaggregate",
            unique_together={("date", "time_grain", "country_slug", "dimension_type", "dimension_value")},
        ),
    ]
