# Generated by Django 5.2.13 on 2026-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_completionaggregate_demographicaggregate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicaggregate',
            name='total_households',
            field=models.IntegerField(default=0),
        ),
    ]
