# Generated by Django 6.0.7 on 2026-08-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0006_demographicaggregate_total_households"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                (
                    "time_grain",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        db_index=True,
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("country_slug", models.CharField(db_index=True, max_length=100)),
                ("dimension_type", models.CharField(db_index=True, max_length=50)),
                ("dimension_value", models.CharField(db_index=True, max_length=255)),
                ("module", models.CharField(db_index=True, max_length=50)),
                ("risk_code", models.CharField(db_index=True, max_length=100)),
                ("risk_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("issue_count", models.IntegerField(default=0)),
                ("percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("unit_label", models.CharField(default="payments", max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("caution", "Caution"),
                            ("normal", "Normal"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[("up", "Increasing"), ("down", "Decreasing"), ("neutral", "Neutral")],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("threshold_info", models.CharField(blank=True, default="", max_length=255)),
                ("is_visible_on_dashboard", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Risk Aggregate",
                "verbose_name_plural": "Risk Aggregates",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["dimension_type", "date"], name="analysis_ri_dimensi_d19fdb_idx"),
                    models.Index(fields=["country_slug", "dimension_type"], name="analysis_ri_country_db9399_idx"),
                    models.Index(
                        fields=["dimension_type", "country_slug", "date", "time_grain"],
                        name="analysis_ri_dimensi_05a6ab_idx",
                    ),
                    models.Index(fields=["module", "severity"], name="analysis_ri_module_1dd438_idx"),
                    models.Index(fields=["risk_code", "date"], name="analysis_ri_risk_co_1548bc_idx"),
                ],
                "unique_together": {("date", "time_grain", "country_slug", "dimension_type", "dimension_value")},
            },
        ),
    ]
