# Generated by Django 6.0.8 on 2026-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0007_riskaggregate"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("risk_code", models.CharField(max_length=100, unique=True)),
                ("module", models.CharField(blank=True, default="", max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("metric", models.TextField(blank=True, default="")),
                ("entity", models.CharField(blank=True, default="", max_length=100)),
                ("threshold", models.CharField(blank=True, default="", max_length=255)),
                ("action", models.TextField(blank=True, default="")),
                ("source_system", models.CharField(blank=True, default="", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fiduciary", "Fiduciary"),
                            ("safeguarding", "Safeguarding"),
                            ("programmatic", "Programmatic"),
                            ("operational", "Operational"),
                            ("compliance", "Compliance"),
                        ],
                        db_index=True,
                        default="operational",
                        max_length=20,
                    ),
                ),
                (
                    "default_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("caution", "Caution"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("country", "Country"), ("both", "Both")],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Risk Definition",
                "verbose_name_plural": "Risk Definitions",
                "ordering": ("module", "risk_code"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="riskaggregate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="riskaggregate",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fiduciary", "Fiduciary"),
                    ("safeguarding", "Safeguarding"),
                    ("programmatic", "Programmatic"),
                    ("operational", "Operational"),
                    ("compliance", "Compliance"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="riskaggregate",
            name="program_name",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="riskaggregate",
            unique_together={
                ("date", "time_grain", "country_slug", "dimension_type", "dimension_value", "program_name")
            },
        ),
        migrations.AddIndex(
            model_name="riskaggregate",
            index=models.Index(fields=["program_name", "date"], name="analysis_ri_program_a23d0d_idx"),
        ),
        migrations.AddIndex(
            model_name="riskaggregate",
            index=models.Index(fields=["category", "date"], name="analysis_ri_categor_f95c7e_idx"),
        ),
    ]
